export type { BatteryInfo } from './battery-info.interface';
export type { BrowserInfo, EmulatedInfo } from './browser-info.interface';
export type { ExtensionContext } from './extension-context.interface';
export type { NetworkInfo } from './network-info.interface.ts';
export type { OSInfo } from './os-info.interface';
export type { MemoryInfo } from './memory-info.interface';
export type { LanguageInfo } from './language-info.interface';
export type { SystemInfo } from './system-info.interface';
export type { ElementDescriptor } from './element-descriptor.interface';
export type { TrackedEvent } from './track-event.interface';
export type { ResizeHandler } from './resize.interface';
