export {
  DRAWING_TOOLS,
  getShadowHostElement,
  getCanvasElement,
  initializeFabric,
  applyBrush,
  handleCanvasMouseDown,
  handleCanvasMouseMove,
  handleCanvasMouseUp,
  handleCanvasObjectModified,
  handlePathCreated,
  handleCanvasObjectMoving,
  handleCanvasSelectionCreated,
  handleCanvasObjectScaling,
  renderCanvas,
  handleResize,
  handleCanvasZoom,
} from '@extension/editor';
