export {
  createRectangle,
  createTriangle,
  createCircle,
  createLine,
  createArrow,
  createBlur,
  createSuggestingBox,
  createText,
  createSpecificShape,
  handleImageUpload,
  setCanvasBackground,
  createShape,
  modifyShape,
  bringElement,
  DEFAULT_BLUR_RADIUS,
} from '@extension/editor';
