export enum SliceStatus {
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  PENDING = 'PENDING',
  DRAFT = 'DRAFT',
  ACCEPTED = 'ACCEPTED',
  REPORTED = 'REPORTED',
}
