name: Auto Assign

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ${{ fromJSON((github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && vars.LOCAL_RUNNER_LABELS || '["ubuntu-latest"]') }}
    permissions:
      pull-requests: write

    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.2
        with:
          configuration-path: '.github/auto_assign.yml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
