name: Run Chromium E2E Tests

on:
  workflow_dispatch:

jobs:
  chrome:
    name: E2E tests for Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm -F @extension/e2e exec playwright install --with-deps --no-shell chromium
      - run: pnpm e2e
